
-- База данных: ISERVDB
-- CREATE DATABASE iservdb;

-- Создание схемы dbo, если не существует
CREATE SCHEMA IF NOT EXISTS dbo;

-- Удаление таблиц (если существуют)
DROP TABLE IF EXISTS dbo.es_tariff CASCADE;

DROP TABLE IF EXISTS dbo.ed_meter_readings CASCADE;

DROP TABLE IF EXISTS dbo.ed_devices CASCADE;

DROP TABLE IF EXISTS dbo.fd_payment_details CASCADE;

DROP TABLE IF EXISTS dbo.fd_payments CASCADE;

DROP TABLE IF EXISTS dbo.fd_bills CASCADE;

DROP TABLE IF EXISTS dbo.dd_docs_assignments CASCADE;

DROP TABLE IF EXISTS dbo.dd_docs CASCADE;

DROP TABLE IF EXISTS dbo.sd_subscrs CASCADE;

-- лицевые счета
CREATE TABLE dbo.sd_subscrs
(
    link         int  NOT NULL GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    c_number     text NOT NULL,
    c_firstname  text NOT NULL,
    c_secondname text NOT NULL,
    c_address    text NULL,
    c_doc_serial text NULL,
    c_doc_number text NULL,
    d_birthdate  date NOT NULL,
    CONSTRAINT uc_sd_subscrs_c_number
        UNIQUE (c_number)
);

-- документы
CREATE TABLE dbo.dd_docs
(
    link       int  NOT NULL GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    c_number   text NULL,
    f_subscr   int  NOT NULL,
    c_doc_type text NOT NULL,
    d_date     date NOT NULL DEFAULT CURRENT_DATE,
    f_docs     int  NULL,
    b_done     boolean,
    CONSTRAINT fk_dd_docs_dd_docs
        FOREIGN KEY (f_docs) REFERENCES dbo.dd_docs (link),
    CONSTRAINT fk_dd_docs_sd_subscrs
        FOREIGN KEY (f_subscr) REFERENCES dbo.sd_subscrs (link) ON DELETE CASCADE
);

-- мероприятия
CREATE TABLE dbo.dd_docs_assignments
(
    link            int  NOT NULL GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    f_docs          int  NOT NULL,
    c_name          text NULL,
    d_needtodo_date date NOT NULL,
    d_done_date     date NULL,
    b_done          boolean,
    CONSTRAINT fk_dd_docs_assignments_dd_docs
        FOREIGN KEY (f_docs) REFERENCES dbo.dd_docs (link) ON DELETE CASCADE
);

-- счета
CREATE TABLE dbo.fd_bills
(
    link          int            NOT NULL GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    c_number      text           NULL,
    f_subscr      int            NOT NULL,
    c_sale_items  text           NOT NULL,
    d_date        date           NOT NULL DEFAULT CURRENT_DATE,
    n_amount      numeric(19, 4) NOT NULL,
    n_amount_rest numeric(19, 4) NOT NULL,
    CONSTRAINT fk_fd_bills_sd_subscrs
        FOREIGN KEY (f_subscr) REFERENCES dbo.sd_subscrs (link) ON DELETE CASCADE
);

-- платежи
CREATE TABLE dbo.fd_payments
(
    link     int            NOT NULL GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    c_number text           NULL,
    f_subscr int            NOT NULL,
    d_date   date           NOT NULL DEFAULT CURRENT_DATE,
    n_amount numeric(19, 4) NOT NULL,
    CONSTRAINT fk_fd_payments_sd_subscrs
        FOREIGN KEY (f_subscr) REFERENCES dbo.sd_subscrs (link) ON DELETE CASCADE
);

-- детализация платежей
CREATE TABLE dbo.fd_payment_details
(
    f_payments   int            NOT NULL,
    f_bills      int            NOT NULL,
    c_sale_items text           NOT NULL,
    n_amount     numeric(19, 4) NOT NULL,
    CONSTRAINT fk_fd_payment_details_fd_payments
        FOREIGN KEY (f_payments) REFERENCES dbo.fd_payments (link) ON DELETE CASCADE,
    CONSTRAINT fk_fd_payment_details_fd_bills
        FOREIGN KEY (f_bills) REFERENCES dbo.fd_bills (link),
    PRIMARY KEY (f_payments, f_bills)
);

CREATE INDEX idc_fd_payment_details ON dbo.fd_payment_details (f_payments);

-- приборы учета
CREATE TABLE dbo.ed_devices
(
    link            int  NOT NULL GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    f_subscr        int  NOT NULL,
    c_name          text NOT NULL,
    c_serial_number text NOT NULL,
    c_sale_items    text NOT NULL,
    d_setup_date    date NOT NULL,
    d_replace_date  date NULL,
    CONSTRAINT fk_ed_devicess_sd_subscrs
        FOREIGN KEY (f_subscr) REFERENCES dbo.sd_subscrs (link) ON DELETE CASCADE
);

-- показания
CREATE TABLE dbo.ed_meter_readings
(
    link      int            NOT NULL GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    f_devices int            NOT NULL,
    d_date    date           NOT NULL,
    n_value   decimal(19, 6) NOT NULL,
    c_status  text           NULL,
    CONSTRAINT fk_ed_meter_readings_ed_devices
        FOREIGN KEY (f_devices) REFERENCES dbo.ed_devices (link) ON DELETE CASCADE
);

-- тарифы
CREATE TABLE dbo.es_tariff
(
    link         int            NOT NULL GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    c_name       text           NOT NULL,
    n_tariff     decimal(19, 6) NOT NULL,
    c_sale_items text           NOT NULL,
    d_date_begin date           NOT NULL,
    d_date_end   date           NULL
);

-- Комментарии к таблицам и столбцам

COMMENT ON TABLE dbo.sd_subscrs IS 'Лицевые счета';

COMMENT ON COLUMN dbo.sd_subscrs.link IS 'Ид';

COMMENT ON COLUMN dbo.sd_subscrs.c_number IS 'Номер лс';

COMMENT ON COLUMN dbo.sd_subscrs.c_firstname IS 'Имя';

COMMENT ON COLUMN dbo.sd_subscrs.c_secondname IS 'Фамилия';

COMMENT ON COLUMN dbo.sd_subscrs.c_address IS 'Адрес регистрации';

COMMENT ON COLUMN dbo.sd_subscrs.c_doc_serial IS 'Серия паспорта';

COMMENT ON COLUMN dbo.sd_subscrs.c_doc_number IS 'Номер паспорта';

COMMENT ON COLUMN dbo.sd_subscrs.d_birthdate IS 'Дата рождения';

COMMENT ON TABLE dbo.dd_docs IS 'Документы';

COMMENT ON COLUMN dbo.dd_docs.link IS 'Ид';

COMMENT ON COLUMN dbo.dd_docs.c_number IS 'Номер';

COMMENT ON COLUMN dbo.dd_docs.f_subscr IS 'Л/с';

COMMENT ON COLUMN dbo.dd_docs.c_doc_type IS 'Тип';

COMMENT ON COLUMN dbo.dd_docs.d_date IS 'Дата';

COMMENT ON COLUMN dbo.dd_docs.f_docs IS 'Родительский документ';

COMMENT ON COLUMN dbo.dd_docs.b_done IS 'Признак исполненного: 1-Да 0-Нет';

COMMENT ON TABLE dbo.dd_docs_assignments IS 'Мероприятия';

COMMENT ON COLUMN dbo.dd_docs_assignments.link IS 'Ид';

COMMENT ON COLUMN dbo.dd_docs_assignments.f_docs IS 'Родительский документ';

COMMENT ON COLUMN dbo.dd_docs_assignments.c_name IS 'Наименование';

COMMENT ON COLUMN dbo.dd_docs_assignments.d_needtodo_date IS 'Плановая дата исполнения';

COMMENT ON COLUMN dbo.dd_docs_assignments.d_done_date IS 'Фактическая дата исполнения';

COMMENT ON COLUMN dbo.dd_docs_assignments.b_done IS 'Признак исполненного: 1-Да 0-Нет';

COMMENT ON TABLE dbo.fd_bills IS 'Счета';

COMMENT ON COLUMN dbo.fd_bills.link IS 'Ид';

COMMENT ON COLUMN dbo.fd_bills.c_number IS 'Номер';

COMMENT ON COLUMN dbo.fd_bills.f_subscr IS 'Л/с';

COMMENT ON COLUMN dbo.fd_bills.c_sale_items IS 'Услуга';

COMMENT ON COLUMN dbo.fd_bills.d_date IS 'Дата';

COMMENT ON COLUMN dbo.fd_bills.n_amount IS 'Сумма';

COMMENT ON COLUMN dbo.fd_bills.n_amount_rest IS 'Остаток';

COMMENT ON TABLE dbo.fd_payments IS 'Платежи';

COMMENT ON COLUMN dbo.fd_payments.link IS 'Ид';

COMMENT ON COLUMN dbo.fd_payments.c_number IS 'Номер';

COMMENT ON COLUMN dbo.fd_payments.f_subscr IS 'Л/с';

COMMENT ON COLUMN dbo.fd_payments.d_date IS 'Дата';

COMMENT ON COLUMN dbo.fd_payments.n_amount IS 'Сумма';

COMMENT ON TABLE dbo.fd_payment_details IS 'Детализация платежей';

COMMENT ON COLUMN dbo.fd_payment_details.f_payments IS 'Ид платежа';

COMMENT ON COLUMN dbo.fd_payment_details.f_bills IS 'Ид счета';

COMMENT ON COLUMN dbo.fd_payment_details.c_sale_items IS 'Услуга';

COMMENT ON COLUMN dbo.fd_payment_details.n_amount IS 'Сумма';

COMMENT ON TABLE dbo.ed_devices IS 'Приборы учета';

COMMENT ON COLUMN dbo.ed_devices.link IS 'Ид';

COMMENT ON COLUMN dbo.ed_devices.f_subscr IS 'Л/с';

COMMENT ON COLUMN dbo.ed_devices.c_name IS 'Наименование';

COMMENT ON COLUMN dbo.ed_devices.c_serial_number IS 'Серийный номер';

COMMENT ON COLUMN dbo.ed_devices.c_sale_items IS 'Услуга';

COMMENT ON COLUMN dbo.ed_devices.d_setup_date IS 'Дата установки';

COMMENT ON COLUMN dbo.ed_devices.d_replace_date IS 'Дата снятия';

COMMENT ON TABLE dbo.ed_meter_readings IS 'Показания';

COMMENT ON COLUMN dbo.ed_meter_readings.link IS 'Ид';

COMMENT ON COLUMN dbo.ed_meter_readings.f_devices IS 'ПУ';

COMMENT ON COLUMN dbo.ed_meter_readings.d_date IS 'Дата показания';

COMMENT ON COLUMN dbo.ed_meter_readings.n_value IS 'Значение';

COMMENT ON COLUMN dbo.ed_meter_readings.c_status IS 'Статус: "Дост", "Недост"';

COMMENT ON TABLE dbo.es_tariff IS 'Тарифы';

COMMENT ON COLUMN dbo.es_tariff.link IS 'Ид';

COMMENT ON COLUMN dbo.es_tariff.c_name IS 'ПУ';

COMMENT ON COLUMN dbo.es_tariff.n_tariff IS 'Значение';

COMMENT ON COLUMN dbo.es_tariff.c_sale_items IS 'Услуга';

COMMENT ON COLUMN dbo.es_tariff.d_date_begin IS 'Дата начала действия';

COMMENT ON COLUMN dbo.es_tariff.d_date_end IS 'Дата окончания действия';

-- Вставка данных

-- sd_subscrs
INSERT INTO dbo.sd_subscrs (c_number, c_firstname, c_secondname, c_address, c_doc_serial, c_doc_number, d_birthdate)
VALUES
    ('10005000', 'Николай', 'Озеров', 'г. Чебоксары, ул. Гагарина, д. 10, кв. 15', '5766', '342456', '1982-07-15'::date),
    ('10005001', 'Сергей', 'Иванов', 'г. Чебоксары, ул. Энгельса, д. 1 кв. 88', '4425', '678942', '1985-02-24'::date),
    ('10005003', 'Елена', 'Елисеева', 'г. Чебоксары, пр-кт. Ленина, д. 8 кв. 104', '2245', '442567', '2010-11-10'::date),
    ('10005002', 'Алексей', 'Федоров', 'г. Чебоксары, пр-кт. Ленина, д. 26 кв. 4', '3435', '567823', '1975-09-04'::date),
    ('10005004', 'Петр', 'Сергеев', 'г. Чебоксары, ул. 324 Стрелковой дивизии, д. 5 кв. 27', '7765', '745832', '2013-03-18'::date),
    ('10005005', 'Руслан', 'Нигматулин', 'д. Хыркасы, д. 9', '5535', '665447', '1990-06-01'::date);

-- dd_docs
INSERT INTO dbo.dd_docs (c_number, f_subscr, c_doc_type, d_date, f_docs, b_done)
VALUES
    ('1-д/1', 1, 'Тип #1', '2019-01-01'::date, NULL, FALSE),
    ('1-д/2', 2, 'Тип #1', '2019-02-02'::date, NULL, FALSE),
    ('1-д/3', 3, 'Тип #1', '2019-01-15'::date, NULL, FALSE),
    ('1-д/4', 4, 'Тип #1', '2018-12-25'::date, NULL, FALSE),
    ('1-д/5', 5, 'Тип #1', '2018-12-12'::date, NULL, FALSE),
    ('2-д/1', 1, 'Тип #6', '2019-01-04'::date, 1, TRUE),
    ('3-д/1', 1, 'Тип #0', '2019-01-12'::date, 6, TRUE),
    ('4-д/1', 1, 'Тип #4', '2019-01-25'::date, 7, FALSE),
    ('5-д/1', 1, 'Тип #9', '2019-02-02'::date, 8, FALSE),
    ('2-д/3', 3, 'Тип #6', '2019-01-18'::date, 3, FALSE),
    ('3-д/3', 3, 'Тип #0', '2019-01-25'::date, 10, FALSE),
    ('6-д/1', 1, 'Тип #3', '2019-01-05'::date, NULL, FALSE),
    ('7-д/1', 1, 'Тип #3', '2019-01-06'::date, NULL, FALSE);

-- dd_docs_assignments
INSERT INTO dbo.dd_docs_assignments (f_docs, c_name, d_needtodo_date, d_done_date, b_done)
VALUES
    (6, 'Позвонить по телефону', '2019-01-01'::date, '2019-01-01'::date, TRUE),
    (7, 'Позвонить по телефону', '2019-01-12'::date, '2019-01-14'::date, TRUE),
    (7, 'Отправить предупреждение по почте', '2019-01-14'::date, NULL, FALSE),
    (8, 'Отправить СМС', '2019-01-25'::date, '2019-01-26'::date, TRUE),
    (9, 'Пересчитать сумму долга', '2019-02-02'::date, NULL, TRUE),
    (9, 'Создать проект искового заявления', '2020-02-09'::date, NULL, FALSE),
    (9, 'Рассчитать сумму госпошлины', '2019-09-09'::date, NULL, FALSE),
    (8, 'Пересчитать сумму долга', '2020-09-09'::date, NULL, FALSE),
    (8, 'Рассчитать сумму госпошлины', '2020-08-17'::date, NULL, FALSE),
    (10, 'Отправить СМС', '2019-04-25'::date, NULL, FALSE),
    (11, 'Позвонить по телефону', '2019-01-12'::date, '2019-05-15'::date, TRUE),
    (10, 'Позвонить по телефону', '2019-05-02'::date, '2019-09-06'::date, TRUE);

-- fd_bills
INSERT INTO dbo.fd_bills (c_number, f_subscr, c_sale_items, d_date, n_amount, n_amount_rest)
VALUES
    ('Счг-1/1', 1::NUMERIC, 'ГВС', '2018-12-05'::date, 150::NUMERIC, 0::NUMERIC),
    ('Счх-1/1', 1::NUMERIC, 'ХВС', '2018-12-08'::date, 100::NUMERIC, 0::NUMERIC),
    ('Счэ-1/1', 1::NUMERIC, 'Э/Э', '2018-12-21'::date, 30::NUMERIC, 0::NUMERIC),
    ('Счг-2/1', 1::NUMERIC, 'ГВС', '2019-01-05'::date, 165::NUMERIC, 0::NUMERIC),
    ('Счх-2/1', 1::NUMERIC, 'ХВС', '2019-01-08'::date, 110::NUMERIC, 0::NUMERIC),
    ('Счэ-2/1', 1::NUMERIC, 'Э/Э', '2019-01-21'::date, 55::NUMERIC, 0::NUMERIC),
    ('Счг-3/1', 1::NUMERIC, 'ГВС', '2019-02-05'::date, 165::NUMERIC, 65::NUMERIC),
    ('Счх-3/1', 1::NUMERIC, 'ХВС', '2019-02-08'::date, 110::NUMERIC, 110::NUMERIC),
    ('Счэ-3/1', 1::NUMERIC, 'Э/Э', '2019-02-21'::date, 55::NUMERIC, 55::NUMERIC),
    ('Счг-4/1', 1::NUMERIC, 'ГВС', '2019-03-01'::date, 165::NUMERIC, 165::NUMERIC),
    ('Счх-4/1', 1::NUMERIC, 'ХВС', '2019-03-01'::date, 110::NUMERIC, 110::NUMERIC),
    ('Счэ-4/1', 1::NUMERIC, 'Э/Э', '2019-03-01'::date, 105::NUMERIC, 105::NUMERIC),
    ('Счг-5/1', 1::NUMERIC, 'ГВС', '2019-04-02'::date, 190::NUMERIC, 190::NUMERIC),
    ('Счх-5/1', 1::NUMERIC, 'ХВС', '2019-04-02'::date, 120::NUMERIC, 120::NUMERIC),
    ('Счэ-5/1', 1::NUMERIC, 'Э/Э', '2019-04-02'::date, 60::NUMERIC, 60::NUMERIC),
    ('Счг-6/1', 1::NUMERIC, 'ГВС', '2019-05-02'::date, 150::NUMERIC, 150::NUMERIC),
    ('Счх-6/1', 1::NUMERIC, 'ХВС', '2019-05-02'::date, 100::NUMERIC, 100::NUMERIC),
    ('Счэ-6/1', 1::NUMERIC, 'Э/Э', '2019-05-02'::date, 80::NUMERIC, 80::NUMERIC),
    ('Счг-7/1', 1::NUMERIC, 'ГВС', '2019-06-01'::date, 140::NUMERIC, 140::NUMERIC),
    ('Счх-7/1', 1::NUMERIC, 'ХВС', '2019-06-01'::date, 160::NUMERIC, 160::NUMERIC),
    ('Счэ-7/1', 1::NUMERIC, 'Э/Э', '2019-06-01'::date, 110::NUMERIC, 110::NUMERIC),
    ('Счг-7/1', 1::NUMERIC, 'ГВС', '2019-12-01'::date, 145::NUMERIC, 145::NUMERIC),
    ('Счх-7/1', 1::NUMERIC, 'ХВС', '2019-12-01'::date, 155::NUMERIC, 155::NUMERIC),
    ('Счэ-7/1', 1::NUMERIC, 'Э/Э', '2019-12-01'::date, 90::NUMERIC, 90::NUMERIC),
    ('Счг-7/1', 1::NUMERIC, 'ГВС', '2020-03-01'::date, 125::NUMERIC, 125::NUMERIC),
    ('Счх-7/1', 1::NUMERIC, 'ХВС', '2020-03-01'::date, 130::NUMERIC, 130::NUMERIC),
    ('Счэ-7/1', 1::NUMERIC, 'Э/Э', '2020-03-01'::date, 60::NUMERIC, 60::NUMERIC),
    ('Счг-1/2', 2::NUMERIC, 'ГВС', '2018-12-11'::date, 170::NUMERIC, 170::NUMERIC),
    ('Счх-1/2', 2::NUMERIC, 'ХВС', '2018-12-14'::date, 105::NUMERIC, 105::NUMERIC),
    ('Счэ-1/2', 2::NUMERIC, 'Э/Э', '2018-12-16'::date, 45::NUMERIC, 45::NUMERIC),
    ('Счг-2/2', 2::NUMERIC, 'ГВС', '2019-01-11'::date, 185::NUMERIC, 185::NUMERIC),
    ('Счх-2/2', 2::NUMERIC, 'ХВС', '2019-01-14'::date, 115::NUMERIC, 115::NUMERIC),
    ('Счэ-2/2', 2::NUMERIC, 'Э/Э', '2019-01-01'::date, 60::NUMERIC, 60::NUMERIC),
    ('Счг-3/2', 2::NUMERIC, 'ГВС', '2019-02-11'::date, 185::NUMERIC, 185::NUMERIC),
    ('Счх-3/2', 2::NUMERIC, 'ХВС', '2019-02-14'::date, 115::NUMERIC, 115::NUMERIC),
    ('Счэ-3/2', 2::NUMERIC, 'Э/Э', '2019-02-16'::date, 60::NUMERIC, 60::NUMERIC);

-- ed_devices
INSERT INTO dbo.ed_devices (f_subscr, c_name, c_serial_number, c_sale_items, d_setup_date, d_replace_date)
VALUES
    (1, 'Меркурий-201.6', '645401798', 'Э/Э', '2019-01-05'::date, NULL),
    (2, 'НЕВА 101 1SO', '01607542', 'Э/Э', '2019-01-05'::date, '2021-05-02'::date),
    (2, 'Меркурий-201.6', '640052506', 'Э/Э', '2021-05-02'::date, NULL),
    (3, 'СКАТ 102 М/1', '4717319 А16', 'Э/Э', '2019-01-05'::date, NULL),
    (4, 'СКАТ 102 М/1', '4140903 А16', 'Э/Э', '2019-01-05'::date, NULL),
    (5, 'Меркурий-201.6', '640052507', 'Э/Э', '2020-09-04'::date, NULL),
    (6, 'Меркурий-201.6', '640052508', 'Э/Э', '2015-10-20'::date, NULL);

-- ed_meter_readings
INSERT INTO dbo.ed_meter_readings (f_devices, d_date, n_value, c_status)
VALUES
    (1::NUMERIC, '2019-01-05'::date, 3::NUMERIC, 'Дост'),
    (1::NUMERIC, '2019-01-25'::date, 150::NUMERIC, 'Дост'),
    (1::NUMERIC, '2019-02-22'::date, 310::NUMERIC, 'Дост'),
    (1::NUMERIC, '2019-03-24'::date, 440::NUMERIC, 'Дост'),
    (1::NUMERIC, '2019-04-21'::date, 600::NUMERIC, 'Дост'),
    (1::NUMERIC, '2019-05-23'::date, 750::NUMERIC, 'Дост'),
    (1::NUMERIC, '2019-06-15'::date, 900::NUMERIC, 'Недост'),
    (1::NUMERIC, '2019-06-20'::date, 910::NUMERIC, 'Дост'),
    (1::NUMERIC, '2019-07-25'::date, 1000::NUMERIC, 'Дост'),
    (2::NUMERIC, '2019-01-05'::date, 3::NUMERIC, 'Дост'),
    (2::NUMERIC, '2019-06-25'::date, 1040::NUMERIC, 'Дост'),
    (2::NUMERIC, '2020-02-22'::date, 2500::NUMERIC, 'Дост'),
    (2::NUMERIC, '2020-07-22'::date, 4500::NUMERIC, 'Дост'),
    (2::NUMERIC, '2021-05-02'::date, 7500::NUMERIC, 'Дост'),
    (3::NUMERIC, '2021-05-02'::date, 3::NUMERIC, 'Дост'),
    (3::NUMERIC, '2021-06-22'::date, 200::NUMERIC, 'Дост'),
    (3::NUMERIC, '2021-07-22'::date, 405::NUMERIC, 'Дост'),
    (3::NUMERIC, '2021-08-15'::date, 620::NUMERIC, 'Недост'),
    (3::NUMERIC, '2021-09-25'::date, 830::NUMERIC, 'Дост'),
    (3::NUMERIC, '2021-10-25'::date, 1005::NUMERIC, 'Недост'),
    (3::NUMERIC, '2021-11-20'::date, 1250.4::NUMERIC, 'Дост'),
    (3::NUMERIC, '2021-12-21'::date, 1500.5::NUMERIC, 'Дост'),
    (3::NUMERIC, '2022-01-20'::date, 1200::NUMERIC, 'Недост'),
    (3::NUMERIC, '2022-02-21'::date, 2000.5::NUMERIC, 'Дост'),
    (3::NUMERIC, '2022-03-21'::date, 2225::NUMERIC, 'Дост');

-- es_tariff
INSERT INTO dbo.es_tariff (c_name, n_tariff, c_sale_items, d_date_begin, d_date_end)
VALUES
    ('Население ээ 2019', 3.5::NUMERIC, 'Э/Э', '2019-01-01'::date, '2019-12-31'::date),
    ('Население ээ 2020', 3.7::NUMERIC, 'Э/Э', '2020-01-01'::date, '2020-12-31'::date),
    ('Население ээ 2021', 3.9::NUMERIC, 'Э/Э', '2021-01-01'::date, '2021-12-31'::date),
    ('Население ээ 2022', 4.1::NUMERIC, 'Э/Э', '2022-01-01'::date, NULL),
    ('Население хвс 2019', 50::NUMERIC, 'ХВС', '2019-01-01'::date, '2019-12-31'::date),
    ('Население хвс 2020', 90::NUMERIC, 'ХВС', '2020-01-01'::date, NULL);

-- fd_payments
INSERT INTO dbo.fd_payments (c_number, f_subscr, d_date, n_amount)
VALUES
    ('П-120', 1::NUMERIC, '2019-01-05'::date, 400::NUMERIC),
    ('П-121', 1::NUMERIC, '2019-02-06'::date, 310::NUMERIC);

-- fd_payment_details
INSERT INTO dbo.fd_payment_details (f_payments, f_bills, c_sale_items, n_amount)
VALUES
    (1::NUMERIC, 1::NUMERIC, 'ГВС', 150::NUMERIC),
    (1::NUMERIC, 2::NUMERIC, 'ХВС', 100::NUMERIC),
    (1::NUMERIC, 3::NUMERIC, 'Э/Э', 30::NUMERIC),
    (1::NUMERIC, 4::NUMERIC, 'ГВС', 120::NUMERIC),
    (2::NUMERIC, 4::NUMERIC, 'ГВС', 45::NUMERIC),
    (2::NUMERIC, 5::NUMERIC, 'ХВС', 110::NUMERIC),
    (2::NUMERIC, 6::NUMERIC, 'Э/Э', 55::NUMERIC),
    (2::NUMERIC, 7::NUMERIC, 'ГВС', 100::NUMERIC);

-- Проверочные SELECT (опционально)
-- SELECT * FROM dbo.sd_subscrs;
-- SELECT * FROM dbo.dd_docs;
-- SELECT * FROM dbo.dd_docs_assignments;
-- SELECT * FROM dbo.fd_bills;
-- SELECT * FROM dbo.fd_payments;
-- SELECT * FROM dbo.fd_payment_details;
-- SELECT * FROM dbo.ed_devices;
-- SELECT * FROM dbo.ed_meter_readings;
-- SELECT * FROM dbo.es_tariff;